@startuml
skinparam monochrome true

participant Main
participant TimeServer
participant TextClock
participant AnalogClock
participant DigitalClock
participant ShadowDecorator

Main -> TimeServer: startServer()

loop every 1 second
    TimeServer -> TimeServer: tick() → timeState++
    TimeServer -> TextClock: update(this)
    TimeServer -> AnalogClock: update(this)
    TimeServer -> DigitalClock: update(this)
    AnalogClock -> ShadowDecorator: checkAndSendMessage() (каждые 60 сек)
    AnalogClock -> GlowDecorator: draw()
    AnalogClock -> ShadowDecorator: draw()
end

@enduml